#!/usr/bin/env sh
# Call this script with 3 parameters, for example
# ./addText <image_file> <letter_of_legend> <output_folder>

cat template.tex | sed "s/_image_/$1/g" | sed "s/_letter_/$2/g" | pdflatex
mv texput.pdf $3/$2_$1 
rm texput.*

exit 0
