#!/usr/bin/env python3
import os

id = "b"
N = 15

with open(f"{id}.txt", "r") as f: nums = f.readlines()

out_folders = [f"{id}{i}" for i in range(N)]

for dest in out_folders:
	os.system(f"mkdir {dest}")

NUM_PER_FOLDER = len(nums)/len(out_folders)

for i, num in enumerate(nums):
	num = num.strip()
	num = num.split("	")[0]
	dest = out_folders[int(i/NUM_PER_FOLDER)]
	os.system(f"./addText {id}.pdf {num} {dest}")

for dest in out_folders:
	os.system(f"pdfunite {dest}/* {dest}.pdf")

os.system(f'7z a {id + ".7z"} {" ".join([of+".pdf" for of in out_folders])}')

